version: 0.2

phases:
  install:
    commands:
      - echo "Installing Java Development Kit (JDK)"
      - apt-get update -y
      - apt-get install -y default-jdk

  build:
    commands:
      - echo "Compiling Java program..."
      - javac HelloWorld.java

  post_build:
    commands:
      - echo "Running the Java program..."
      - java HelloWorld

artifacts:
  files:
    - HelloWorld.class
